@contentType = multipart/form-data;

### Register

POST {{$dotenv ROOT_DIR}}/api/register.php 
Content-Type: {{contentType}} boundary=----register

------register
Content-Disposition: form-data; name="phone"

+8801943253440
------register
Content-Disposition: form-data; name="password"

12345678
------register--

### Login

POST {{$dotenv ROOT_DIR}}/api/login.php 
Content-Type: {{contentType}} boundary=----login

------login
Content-Disposition: form-data; name="phone"

+8801943253440
------login
Content-Disposition: form-data; name="password"

12345678
------login--

### Is Logged In

POST {{$dotenv ROOT_DIR}}/api/is-logged-in.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----is-logged-in
------is-logged-in--

### Read Categories

POST {{$dotenv ROOT_DIR}}/api/read-categories.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----read-categories
------read-categories--

### Read Category by Id

POST {{$dotenv ROOT_DIR}}/api/read-category-by-id.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----read-category-by-id

------read-category-by-id
Content-Disposition: form-data; name="id"

1
------read-category-by-id--

### Read Topics by Category Id

POST {{$dotenv ROOT_DIR}}/api/read-topics-by-category-id.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----read-topics-by-category-id

------read-topics-by-category-id
Content-Disposition: form-data; name="categoryId"

1
------read-topics-by-category-id--

### Read Topic by Id

POST {{$dotenv ROOT_DIR}}/api/read-topic-by-id.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----read-topic-by-id

------read-topic-by-id
Content-Disposition: form-data; name="id"

8
------read-topic-by-id--

### Read Quiz by Topic Id

POST {{$dotenv ROOT_DIR}}/api/read-quiz-by-topic-id.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----read-quiz-by-topic-id

------read-quiz-by-topic-id
Content-Disposition: form-data; name="topicId"

9
------read-quiz-by-topic-id--

### Create Score

POST {{$dotenv ROOT_DIR}}/api/create-score.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----create-score

------create-score
Content-Disposition: form-data; name="topicId"

8
------create-score
Content-Disposition: form-data; name="answers"

[
  {
    "questionId": 1, 
    "chosenOptions": ["1"]
  },
  {
    "questionId": 2, 
    "chosenOptions": ["3"]
  },
  {
    "questionId": 3, 
    "chosenOptions": ["0", "2"]
  },
  {
    "questionId": 4, 
    "chosenOptions": ["0"]
  },
  {
    "questionId": 5, 
    "chosenOptions": ["0"]
  }
]
------create-score--

### Read Scores

POST {{$dotenv ROOT_DIR}}/api/read-scores.php 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEyIn0.PZStAskQ4G3Q0uKHUmxwb81xVhOk3rLPJzy4sJtzw0M
Content-Type: {{contentType}} boundary=----read-scores
------read-scores--